apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendee-worker
  namespace: attendee
  labels:
    app: attendee-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendee-worker
  template:
    metadata:
      labels:
        app: attendee-worker
    spec:
      containers:
        - name: attendee-worker
          image: ghcr.io/hjs48/attendee:latest
          imagePullPolicy: Always
          command: ["celery"]
          args:
            - "-A"
            - "attendee"
            - "worker"
            - "--loglevel=info"
            - "--concurrency=2"
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
