apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"attendee-bot-creator-binding","namespace":"attendee"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"bot-pod-manager"},"subjects":[{"kind":"ServiceAccount","name":"attendee-bot-creator","namespace":"attendee"}]}
    creationTimestamp: "2026-01-19T14:16:27Z"
    name: attendee-bot-creator-binding
    namespace: attendee
    resourceVersion: "836"
    uid: 5489b409-3b49-40c9-aabd-8c4925ccd3ca
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: bot-pod-manager
  subjects:
  - kind: ServiceAccount
    name: attendee-bot-creator
    namespace: attendee
kind: List
metadata:
  resourceVersion: ""
