apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"bot-creator","app.kubernetes.io/name":"attendee"},"name":"attendee-bot-creator","namespace":"attendee"}}
    creationTimestamp: "2026-01-19T14:16:27Z"
    labels:
      app.kubernetes.io/component: bot-creator
      app.kubernetes.io/name: attendee
    name: attendee-bot-creator
    namespace: attendee
    resourceVersion: "834"
    uid: 4884eef4-afe4-4947-a8ca-4d2972429428
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-01-19T14:13:59Z"
    name: default
    namespace: attendee
    resourceVersion: "785"
    uid: cbdafcb1-00de-45fd-a816-8948b3c9ecfc
kind: List
metadata:
  resourceVersion: ""
